spring:
  application:
    name: GreetAPI-Service
  boot:
    admin:
      client:
        url: http://localhost:1111/
#Configure actuator end point
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9091
  
