spring:
  application:
    name: Welcome-API
    #Making REST API as client to the Admin server
  boot:
    admin:
      client:
        url: http://localhost:1111/
#Managing actuators
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
server:
  port: 8081